version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/integrations/vanilla-bubbles"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  - package-ecosystem: "npm"
    directory: "/integrations/react-bubbles"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  - package-ecosystem: "npm"
    directory: "/integrations/vue-bubbles"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  - package-ecosystem: "npm"
    directory: "/integrations/svelte-bubbles"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
